import type { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    id: '1',
    name: 'Quantum DB',
    tagline: 'A blazing fast, in-memory database for real-time applications.',
    description: 'Quantum DB is a high-performance, in-memory database designed for applications that require instantaneous data access and processing. Built with Rust, it guarantees thread-safety and unparalleled speed, making it perfect for financial trading platforms, real-time analytics, and gaming backends.',
    price: 199.99,
    features: [
      'Sub-millisecond latency',
      'ACID compliant transactions',
      'Scalable to millions of operations per second',
      'Written in Rust for maximum safety and performance',
    ],
    imageId: 'project1',
    encoding: 'UTF-8',
  },
  {
    id: '2',
    name: 'CogniGenius AI',
    tagline: 'An advanced AI component for natural language understanding.',
    description: 'Integrate sophisticated natural language processing into your applications with CogniGenius AI. This component provides a simple API to understand, analyze, and respond to human language with remarkable accuracy. Ideal for chatbots, customer support automation, and content analysis.',
    price: 249.00,
    features: [
      'Sentiment analysis',
      'Entity recognition',
      'Language detection and translation',
      'Easy to integrate REST API',
    ],
    imageId: 'project2',
    encoding: 'UTF-8',
  },
  {
    id: '3',
    name: 'SecureAuth Kit',
    tagline: 'A complete authentication solution for modern web apps.',
    description: 'SecureAuth Kit provides a robust, out-of-the-box authentication and user management solution. It handles everything from secure sign-up and login to multi-factor authentication and social logins, allowing you to focus on your core application features. Compliant with OAuth 2.0 and OpenID Connect.',
    price: 99.50,
    features: [
      'Social logins (Google, GitHub)',
      'Multi-factor authentication (MFA)',
      'Role-based access control (RBAC)',
      'Secure session management',
    ],
    imageId: 'project3',
    encoding: 'UTF-8',
  },
  {
    id: '4',
    name: 'RenderFlow Engine',
    tagline: 'A real-time 3D rendering engine for web and mobile.',
    description: 'Bring stunning 3D graphics to your applications with RenderFlow Engine. This lightweight, powerful rendering engine is optimized for WebGL 2.0 and provides a complete toolset for creating interactive 3D experiences. It includes a scene graph, material system, and physics integration.',
    price: 350.00,
    features: [
      'Physically-based rendering (PBR)',
      'Advanced lighting and shadow effects',
      'GLTF 2.0 model support',
      'Cross-platform compatibility',
    ],
    imageId: 'project4',
    encoding: 'UTF-8',
  },
  {
    id: '5',
    name: 'DataWeave ETL',
    tagline: 'A flexible data extraction, transformation, and loading toolkit.',
    description: 'Simplify your data pipelines with DataWeave ETL. This versatile toolkit allows you to easily connect to various data sources, transform data with a simple yet powerful scripting language, and load it into any destination. Perfect for data warehousing, business intelligence, and data migration tasks.',
    price: 499.00,
    features: [
      'Connectors for 50+ data sources',
      'Intuitive data mapping UI',
      'Scalable processing engine',
      'Job scheduling and monitoring',
    ],
    imageId: 'project5',
    encoding: 'UTF-16',
  },
  {
    id: '6',
    name: 'PixelPerfect UI Kit',
    tagline: 'A comprehensive component library for React.',
    description: 'Build beautiful, accessible, and responsive user interfaces faster than ever with PixelPerfect UI Kit. This library offers a wide range of professionally designed and fully customizable React components, following the best practices for design and accessibility.',
    price: 79.00,
    features: [
      '50+ customizable components',
      'Built-in theme support and dark mode',
      'WCAG 2.1 AA compliant',
      'Detailed documentation and examples',
    ],
    imageId: 'project6',
    encoding: 'UTF-8',
  },
];
