import type { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    id: '1',
    name: 'SEO (posicionamiento web)',
    tagline: 'Optimiza tu sitio web para alcanzar las primeras posiciones en los buscadores.',
    description: 'Este servicio integral de SEO aumenta tu visibilidad online, atrae tráfico orgánico de calidad y mejora tu posicionamiento en los motores de búsqueda. Analizamos tu web, encontramos oportunidades y aplicamos las mejores prácticas para superar a tu competencia.',
    price: 15000.00,
    category: 'Servicio Digital',
    features: [
      'Auditoría SEO completa',
      'Investigación de palabras clave',
      'Optimización On-Page y técnica',
      'Estrategia de Link Building',
      'Informes de rendimiento mensuales',
    ],
    imageId: 'project1',
    encoding: 'UTF-8',
  },
  {
    id: '2',
    name: 'Inteligencia Artificial',
    tagline: 'Un componente avanzado de IA para la comprensión del lenguaje natural.',
    description: 'Integra un sofisticado procesamiento de lenguaje natural en tus aplicaciones con este componente de Inteligencia Artificial. Proporciona una API simple para comprender, analizar y responder al lenguaje humano con una precisión notable. Ideal para chatbots, automatización de soporte al cliente y análisis de contenido.',
    price: 24900.00,
    category: 'Proyecto de Programación',
    features: [
      'Análisis de sentimiento',
      'Reconocimiento de entidades',
      'Detección y traducción de idiomas',
      'API REST fácil de integrar',
    ],
    imageId: 'project2',
    encoding: 'UTF-8',
  },
  {
    id: '7',
    name: 'Portafolio Minimalista',
    tagline: 'Una plantilla de sitio web elegante y moderna para creativos.',
    description: 'Muestra tu trabajo con esta plantilla de portafolio minimalista y limpia. Diseñada con un enfoque en la tipografía y el espacio en blanco, hace que tus proyectos brillen. Totalmente responsiva y fácil de personalizar.',
    price: 4999.0,
    category: 'Diseño Web',
    features: [
      'Diseño limpio y moderno',
      'Totalmente responsivo',
      'Animaciones sutiles',
      'Formulario de contacto funcional',
    ],
    imageId: 'project7',
  },
  {
    id: '3',
    name: 'SecureAuth Kit',
    tagline: 'Una solución de autenticación completa para aplicaciones web modernas.',
    description: 'SecureAuth Kit proporciona una solución robusta y lista para usar de autenticación y gestión de usuarios. Se encarga de todo, desde el registro y el inicio de sesión seguros hasta la autenticación multifactor y los inicios de sesión sociales, permitiéndote centrarte en las características principales de tu aplicación. Cumple con OAuth 2.0 y OpenID Connect.',
    price: 9950.50,
    category: 'Proyecto de Programación',
    features: [
      'Inicios de sesión sociales (Google, GitHub)',
      'Autenticación multifactor (MFA)',
      'Control de acceso basado en roles (RBAC)',
      'Gestión segura de sesiones',
    ],
    imageId: 'project3',
    encoding: 'UTF-8',
  },
  {
    id: '8',
    name: 'E-commerce Moderno',
    tagline: 'Un diseño de tienda online vibrante y atractivo.',
    description: 'Lanza tu tienda online con este diseño de e-commerce moderno y llamativo. Optimizado para la conversión, con páginas de productos claras, un proceso de pago intuitivo y un diseño totalmente responsivo.',
    price: 8999.0,
    category: 'Diseño Web',
    features: [
      'Diseño optimizado para la conversión',
      'Cuadrícula de productos personalizable',
      'Proceso de pago simplificado',
      'Diseño adaptable a móviles',
    ],
    imageId: 'project8',
  },
  {
    id: '6',
    name: 'PixelPerfect UI Kit',
    tagline: 'Una completa biblioteca de componentes para React.',
    description: 'Construye interfaces de usuario hermosas, accesibles y responsivas más rápido que nunca con PixelPerfect UI Kit. Esta biblioteca ofrece una amplia gama de componentes de React diseñados profesionalmente y totalmente personalizables, siguiendo las mejores prácticas de diseño y accesibilidad.',
    price: 7900.00,
    category: 'Proyecto de Programación',
    features: [
      'Más de 50 componentes personalizables',
      'Soporte de temas y modo oscuro incorporados',
      'Cumple con WCAG 2.1 AA',
      'Documentación detallada y ejemplos',
    ],
    imageId: 'project6',
    encoding: 'UTF-8',
  },
];
