import type { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    id: '1',
    name: 'Quantum DB',
    tagline: 'Una base de datos en memoria ultrarrápida para aplicaciones en tiempo real.',
    description: 'Quantum DB es una base de datos en memoria de alto rendimiento diseñada para aplicaciones que requieren acceso y procesamiento de datos instantáneos. Construida con Rust, garantiza seguridad en hilos y una velocidad incomparable, lo que la hace perfecta para plataformas de trading financiero, análisis en tiempo real y backends de juegos.',
    price: 19999.99,
    features: [
      'Latencia inferior al milisegundo',
      'Transacciones compatibles con ACID',
      'Escalable a millones de operaciones por segundo',
      'Escrito en Rust para máxima seguridad y rendimiento',
    ],
    imageId: 'project1',
    encoding: 'UTF-8',
  },
  {
    id: '2',
    name: 'CogniGenius AI',
    tagline: 'Un componente avanzado de IA para la comprensión del lenguaje natural.',
    description: 'Integra un sofisticado procesamiento de lenguaje natural en tus aplicaciones con CogniGenius AI. Este componente proporciona una API simple para comprender, analizar y responder al lenguaje humano con una precisión notable. Ideal para chatbots, automatización de soporte al cliente y análisis de contenido.',
    price: 24900.00,
    features: [
      'Análisis de sentimiento',
      'Reconocimiento de entidades',
      'Detección y traducción de idiomas',
      'API REST fácil de integrar',
    ],
    imageId: 'project2',
    encoding: 'UTF-8',
  },
  {
    id: '3',
    name: 'SecureAuth Kit',
    tagline: 'Una solución de autenticación completa para aplicaciones web modernas.',
    description: 'SecureAuth Kit proporciona una solución robusta y lista para usar de autenticación y gestión de usuarios. Se encarga de todo, desde el registro y el inicio de sesión seguros hasta la autenticación multifactor y los inicios de sesión sociales, permitiéndote centrarte en las características principales de tu aplicación. Cumple con OAuth 2.0 y OpenID Connect.',
    price: 9950.50,
    features: [
      'Inicios de sesión sociales (Google, GitHub)',
      'Autenticación multifactor (MFA)',
      'Control de acceso basado en roles (RBAC)',
      'Gestión segura de sesiones',
    ],
    imageId: 'project3',
    encoding: 'UTF-8',
  },
  {
    id: '4',
    name: 'RenderFlow Engine',
    tagline: 'Un motor de renderizado 3D en tiempo real para web y móviles.',
    description: 'Lleva impresionantes gráficos 3D a tus aplicaciones con RenderFlow Engine. Este motor de renderizado ligero y potente está optimizado para WebGL 2.0 y proporciona un conjunto de herramientas completo para crear experiencias 3D interactivas. Incluye un grafo de escena, sistema de materiales e integración de físicas.',
    price: 35000.00,
    features: [
      'Renderizado basado en físicas (PBR)',
      'Efectos avanzados de iluminación y sombras',
      'Soporte para modelos GLTF 2.0',
      'Compatibilidad multiplataforma',
    ],
    imageId: 'project4',
    encoding: 'UTF-8',
  },
  {
    id: '5',
    name: 'DataWeave ETL',
    tagline: 'Un kit de herramientas flexible para extracción, transformación y carga de datos.',
    description: 'Simplifica tus pipelines de datos con DataWeave ETL. Este versátil kit de herramientas te permite conectarte fácilmente a diversas fuentes de datos, transformar datos con un lenguaje de scripting simple pero potente y cargarlos en cualquier destino. Perfecto para data warehousing, inteligencia de negocios y tareas de migración de datos.',
    price: 49900.00,
    features: [
      'Conectores para más de 50 fuentes de datos',
      'Interfaz de mapeo de datos intuitiva',
      'Motor de procesamiento escalable',
      'Programación y monitoreo de trabajos',
    ],
    imageId: 'project5',
    encoding: 'UTF-16',
  },
  {
    id: '6',
    name: 'PixelPerfect UI Kit',
    tagline: 'Una completa biblioteca de componentes para React.',
    description: 'Construye interfaces de usuario hermosas, accesibles y responsivas más rápido que nunca con PixelPerfect UI Kit. Esta biblioteca ofrece una amplia gama de componentes de React diseñados profesionalmente y totalmente personalizables, siguiendo las mejores prácticas de diseño y accesibilidad.',
    price: 7900.00,
    features: [
      'Más de 50 componentes personalizables',
      'Soporte de temas y modo oscuro incorporados',
      'Cumple con WCAG 2.1 AA',
      'Documentación detallada y ejemplos',
    ],
    imageId: 'project6',
    encoding: 'UTF-8',
  },
];
